const knex = require('./connect');

knex.schema.createTable('users', t => {
  t.increments()
  t.string('name')
  t.string('token')
  t.string('domain')
  t.timestamps()
})
.createTable('bills', t => {
  t.increments()
  t.timestamps()
  t.string('device', 32)
  t.string('nonce_str', 32)
  t.string('sign', 32)
  t.string('sign_type', 32)
  t.string('prd_title')
  t.string('prd_detail')
  t.integer('prd_fee')
  t.string('cst_no', 32)
  t.string('cst_ip', 16)
  t.string('notify_url')
  t.string('user_id')
  t.string('pay_type', 32)
  t.string('trade_type')
  t.string('fee_type', 16).defaultTo('cny')
  t.timestamp('time_start')
  t.timestamp('time_expire')
})
.then(res => console.log(res))
